### ISSUE TITLE
Docker build command fails

### ISSUE THREAD

**Issue by lukehedger** [TrueBitFoundation/truebit-toolchain#5]
The documented Docker build command fails:
```sh
→ docker build . -t truebit-toolchain:latest
docker: "build" requires 1 argument.
```

I have tried this command, inline [with the format](https://docs.docker.com/engine/reference/commandline/build/) `docker build [OPTIONS] PATH ` but it just hangs:
```
docker build -t truebit-toolchain:latest .
```

**Comment by hswick** [comment]
I can see how that is confusing, but this seems like an issue with docker. I can only recommend doing it the way as it is described in the readme:
```
docker build . -t truebit-toolchain:latest
```
